name: "Generate summary"

on:
  push:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python
      - run: python main.py
      - run: $GITHUB_STEP_SUMMARY=$(<table.md)
